spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.200:8848
    gateway:
      routes:
        - id: member_route
          uri: lb://cloud-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: product_route
          uri: lb://cloud-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: lb://cloud-third-party
          predicates:
            - Path=/api/third/party/**
          filters:
            - RewritePath=/api/third/party/(?<segment>/?.*), /$\{segment}

        - id: ware_route
          uri: lb://cloud-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: admin_route
          # 负载均衡到该模块，后面写的是模块名。
          uri: lb://renren-fast
          predicates:
            # 断言，让所有带/api的路径都转发到 renren-fast模块
            - Path=/api/**
          filters:
            # 路径重写,访问默认需要加上context-path
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
        # 检索相关的请求
        - id: gulimall-search
          uri: lb://cloud-search
          predicates:
            - Host=search.gulimall.com
        # 前台相关路由
        - id: gulimall-front
          uri: lb://cloud-product
          predicates:
            - Host=**.gulimall.com,gulimall.com

  application:
    name: cloud-gateway
server:
  port: 88
