spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8848
    alicloud:
      access-key: LTAI5tL3Zfk9sar1bVvPqi1o
      secret-key: ltR88LdcktsrDXw0PeQl3cpLcvd8X5
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-hugh
  application:
    name: cloud-third-party
  mail:
    host: smtp.163.com
    username: linqibin0826@163.com
    password: IBVIQKZUTDAKVBSC

server:
  port: 30000
