spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4Fym3yMo4wvUnn98yFuX
      secret-key: WTk7ZRWcUxoEWud57J42Hvz8K9AkCU
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-hugh
  application:
    name: cloud-third-party
server:
  port: 30000
