spring:
  cloud:
    nacos:
      discovery:
        server-addr: server.home.com:8848
    alicloud:
      access-key: LTAI5tL3Zfk9sar1bVvPqi1o
      secret-key: ltR88LdcktsrDXw0PeQl3cpLcvd8X5
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: mall-hugh
  application:
    name: cloud-third-party
server:
  port: 30000
