server:
  port: 9090

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.12:53316/mall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8848
  application:
    name: cloud-order
  rabbitmq:
    addresses: 192.168.112
    password: 123456
    username: admin
    virtual-host: /

  session:
    store-type: redis
  redis:
    host: 192.168.1.12
    password: 121421

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

gulimall:
  thread:
    core-size: 12
    max-size: 24
    keep-alive-time: 10
