server:
  port: 10000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.12:53316/mall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8848

  application:
    name: cloud-product
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.12
    port: 6379
    password: 121421
  # 指定缓存类型为redis
  cache:
    type: redis
    redis:
      time-to-live: 86400
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.linqibin.mall: debug

gulimall:
  thread:
    core-size: 12
    max-size: 24
    keep-alive-time: 10
