server:
  port: 12000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.12:53316/mall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8848
  application:
    name: cloud-ware

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
