spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.200:8848
  application:
    name: cloud-search
  redis:
    password: 121421
    host: 192.168.1.200
server:
  port: 9999
ipAddr: 192.168.1.200
